# Generated by Django 3.2.5 on 2021-08-01 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_code', models.CharField(max_length=6)),
                ('title', models.CharField(max_length=180, verbose_name='Job title')),
                ('tag', models.CharField(choices=[('Telecommunication', 'Telecommunication'), ('Hospitality', 'Hospitality'), ('Tourism', 'Tourism'), ('Media', 'Mass media'), ('Healthcare', 'Healthcare/Hospitals'), ('Pharmacy', 'Pharmacy'), ('IT', 'Information technology'), ('Waste', 'Waste disposal'), ('Consulting', 'Consulting'), ('Sales', 'Retail sales'), ('FMCG', 'Fast-moving consumer goods (FMCG)'), ('Franchising', 'Franchising'), ('Real-estate', 'Real-estate'), ('Education', 'Education'), ('Financial_services', 'Financial services'), ('Banking', 'Banking'), ('Insurance', 'Insurance'), ('Investment_management', 'Investment management'), ('Professional_services', 'Professional services'), ('Legal_services', 'Legal services'), ('Management_consulting', 'Management consulting'), ('Transportation', 'Transportation'), ('Teaching', 'Teaching'), ('Others', 'Others')], max_length=32, null=True)),
                ('contact', models.CharField(max_length=10, verbose_name='Contact info')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Job deadline')),
                ('location', models.CharField(blank=True, max_length=180, null=True)),
                ('pay_scale', models.PositiveIntegerField(blank=True, null=True, verbose_name='Wage cost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProvideService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_code', models.CharField(max_length=6)),
                ('title', models.CharField(max_length=180)),
                ('contact', models.CharField(max_length=10)),
                ('skills', models.CharField(blank=True, max_length=180)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('pay_scale', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_code', models.CharField(max_length=6, verbose_name='PIN CODE')),
                ('name', models.CharField(blank=True, max_length=18, null=True, verbose_name='Full name')),
                ('contact', models.CharField(blank=True, max_length=10, null=True, verbose_name='Contact info')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=6, null=True)),
                ('availabiity', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks_pulled', models.PositiveIntegerField(blank=True, null=True)),
                ('jobs_given', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
