# Generated by Django 3.2.5 on 2021-08-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestservice',
            name='tag',
            field=models.CharField(choices=[('Telecommunication', 'Telecommunication'), ('Hospitality', 'Hospitality'), ('Tourism', 'Tourism'), ('Media Media', 'Mass Media'), ('Healthcare/Hospitals', 'Healthcare/Hospitals'), ('Pharmacy', 'Pharmacy'), ('Information Technology', 'Information Technology'), ('Waste Disposal', 'Waste Disposal'), ('Consulting', 'Consulting'), ('Retail Sales', 'Retail Sales'), ('Fast-moving consumer goods (FMCG)', 'Fast-moving consumer goods (FMCG)'), ('Franchising', 'Franchising'), ('Real-Estate', 'Real-Estate'), ('Education', 'Education'), ('Financial Services', 'Financial Services'), ('Banking', 'Banking'), ('Insurance', 'Insurance'), ('Investment Management', 'Investment Management'), ('Professional Services', 'Professional Services'), ('Legal Services', 'Legal Services'), ('Management Consulting', 'Management Consulting'), ('Transportation', 'Transportation'), ('Teaching', 'Teaching'), ('Others', 'Others')], max_length=64, null=True),
        ),
    ]
