# Generated by Django 3.2.5 on 2021-08-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_requestservice_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provideservice',
            name='skills',
        ),
        migrations.AddField(
            model_name='provideservice',
            name='tag',
            field=models.CharField(choices=[('Domestic', 'Domestic'), ('Education', 'Education'), ('Teaching', 'Teaching'), ('Telecommunication', 'Telecommunication'), ('Hospitality', 'Hospitality'), ('Tourism', 'Tourism'), ('Mass-Media', 'Mass-Media'), ('Healthcare/Hospitals', 'Healthcare/Hospitals'), ('Pharmacy', 'Pharmacy'), ('Information-Technology', 'Information-Technology'), ('Waste Disposal', 'Waste Disposal'), ('Consulting', 'Consulting'), ('Retail Sales', 'Retail Sales'), ('FMCG', 'FMCG'), ('Franchising', 'Franchising'), ('Real-Estate', 'Real-Estate'), ('Financial Services', 'Financial Services'), ('Banking', 'Banking'), ('Insurance', 'Insurance'), ('Investment Management', 'Investment Management'), ('Professional Services', 'Professional Services'), ('Legal Services', 'Legal Services'), ('Management Consulting', 'Management Consulting'), ('Transportation', 'Transportation'), ('Others', 'Others')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='availabiity',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='provideservice',
            name='contact',
            field=models.CharField(max_length=10, verbose_name='Contact info'),
        ),
        migrations.AlterField(
            model_name='provideservice',
            name='location',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='provideservice',
            name='pay_scale',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Expected paycheck'),
        ),
        migrations.AlterField(
            model_name='requestservice',
            name='tag',
            field=models.CharField(choices=[('Domestic', 'Domestic'), ('Education', 'Education'), ('Teaching', 'Teaching'), ('Telecommunication', 'Telecommunication'), ('Hospitality', 'Hospitality'), ('Tourism', 'Tourism'), ('Mass-Media', 'Mass-Media'), ('Healthcare/Hospitals', 'Healthcare/Hospitals'), ('Pharmacy', 'Pharmacy'), ('Information-Technology', 'Information-Technology'), ('Waste Disposal', 'Waste Disposal'), ('Consulting', 'Consulting'), ('Retail Sales', 'Retail Sales'), ('FMCG', 'FMCG'), ('Franchising', 'Franchising'), ('Real-Estate', 'Real-Estate'), ('Financial Services', 'Financial Services'), ('Banking', 'Banking'), ('Insurance', 'Insurance'), ('Investment Management', 'Investment Management'), ('Professional Services', 'Professional Services'), ('Legal Services', 'Legal Services'), ('Management Consulting', 'Management Consulting'), ('Transportation', 'Transportation'), ('Others', 'Others')], max_length=64, null=True),
        ),
    ]
