# Generated by Django 3.2.5 on 2021-08-03 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_auto_20210803_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='jobs_given',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='tasks_pulled',
        ),
        migrations.AddField(
            model_name='notification',
            name='ask_amount',
            field=models.PositiveIntegerField(null=True, verbose_name='Expected paycheck'),
        ),
        migrations.AddField(
            model_name='notification',
            name='contact',
            field=models.CharField(max_length=10, null=True, verbose_name='Contact info'),
        ),
        migrations.AddField(
            model_name='notification',
            name='job_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='job_title',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='pin_code',
            field=models.CharField(max_length=6, null=True, verbose_name='PIN CODE'),
        ),
        migrations.AddField(
            model_name='notification',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='requester_rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True),
        ),
    ]
