# Generated by Django 3.2.5 on 2021-08-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210803_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='applied_to',
            field=models.TextField(null=True),
        ),
    ]
