# Generated by Django 3.2.6 on 2021-08-04 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_person_applied_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='asked_for',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='employer_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.CreateModel(
            name='HiringAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.PositiveIntegerField(null=True)),
                ('task_title', models.CharField(max_length=180, null=True)),
                ('pin_code', models.CharField(max_length=6, null=True, verbose_name='PIN CODE')),
                ('contact', models.CharField(max_length=10, null=True, verbose_name='Contact info')),
                ('bid_amount', models.PositiveIntegerField(null=True, verbose_name='Expected budget')),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freelancer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
