# Generated by Django 3.2.6 on 2021-08-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210804_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringalert',
            name='employer_rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
