# Generated by Django 3.2.6 on 2021-08-08 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_hiringalert_employer_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='rating',
            new_name='employability',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='availabiity',
            new_name='visibility',
        ),
        migrations.RemoveField(
            model_name='person',
            name='applied_to',
        ),
        migrations.RemoveField(
            model_name='person',
            name='asked_for',
        ),
    ]
