# Generated by Django 3.2.6 on 2021-08-08 05:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0009_auto_20210808_1111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='JobAlert',
        ),
    ]
