# Generated by Django 3.2.6 on 2021-08-08 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_notification_jobalert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiringalert',
            name='employer_rating',
        ),
        migrations.RemoveField(
            model_name='hiringalert',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='hiringalert',
            name='task_title',
        ),
        migrations.RemoveField(
            model_name='jobalert',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='jobalert',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='jobalert',
            name='requester_rating',
        ),
        migrations.AddField(
            model_name='hiringalert',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='user.provideservice'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='user.requestservice'),
        ),
    ]
