# Generated by Django 3.2.6 on 2021-08-08 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210808_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringalert',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='user.person'),
        ),
        migrations.AlterField(
            model_name='jobalert',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='user.person'),
        ),
    ]
